const data = [
  { id: 1, name: 'Gundapu Ravindar (Thalla Police)', money: 500, address: 'NA', status: 0 },
  { id: 2, name: 'Gunda Kumaraswamy (Kiranam)', money: 201, address: 'NA', status: 0 },
  { id: 3, name: 'Gundapu Charan Patel', money: 301, address: 'NA', status: 0 },
  { id: 4, name: 'Gundapu Babu (s/o Ramaswamy)', money: 500, address: 'NA', status: 0 },
  { id: 5, name: 'Bollena Ramcharan Patel', money: 200, address: 'NA', status: 0 },
  { id: 6, name: 'Kasula Rambraham', money: 200, address: 'NA', status: 0 },
  { id: 7, name: 'Cheraku Rajaiah', money: 516, address: 'NA', status: 0 },
  { id: 8, name: 'Kothakonda Rajendar', money: 200, address: 'NA', status: 0 },
  { id: 9, name: 'MD Yakub Ahmed (Pedha)', money: 500, address: 'NA', status: 0 },
  { id: 10, name: 'Kothakonda Shanker', money: 200, address: 'NA', status: 0 },
  { id: 11, name: 'Nutenki Nagesh (s/o Pochaiah)', money: 516, address: 'NA', status: 0 },
  { id: 12, name: 'Gundapu Sadaiah (s/o Malliah)', money: 500, address: 'NA', status: 0 },
  { id: 13, name: 'Gundapu Mallaiah (s/o Odelu)', money: 200, address: 'NA', status: 0 },
  { id: 14, name: 'Gundapu Rajaiah (Thalla s/o Komuraiah)', money: 200, address: 'NA', status: 0 },
  { id: 15, name: 'Kaavati Sadaiah', money: 501, address: 'NA', status: 0 },
  { id: 16, name: 'Eggadi Pedha Thirupathi', money: 216, address: 'NA', status: 0 },
  { id: 17, name: 'Gundapu Lingamurthy (NIT)', money: 201, address: 'NA', status: 0 },
  { id: 18, name: 'Gundapu Sadaiah', money: 201, address: 'NA', status: 0 },
  { id: 19, name: 'Nallala Srikanth', money: 100, address: 'NA', status: 0 },
  { id: 20, name: 'Soora Buchanna', money: 200, address: 'Yellampelly', status: 0 },
  { id: 21, name: 'Gundapu Odelu', money: 200, address: 'Godarkani', status: 0 },
  { id: 22, name: 'Gundapu Santhosh (Police)', money: 1000, address: 'Hanamkonda', status: 0 },
  { id: 23, name: 'Gundapu Srinivas (s/o Lingaiah)', money: 516, address: 'Hanamkonda', status: 0 },
  { id: 24, name: 'Gundapu Rajaiah (s/o Laxmaiah)', money: 200, address: 'NA', status: 0 },
  { id: 25, name: 'Kaavati Thirupathi', money: 200, address: 'NA', status: 0 },
  { id: 26, name: 'Kaavati Shivakumar (s/o Saraiah)', money: 200, address: 'NA', status: 0 },
  { id: 27, name: 'Madipelli Ashok', money: 200, address: 'NA', status: 0 },
  { id: 28, name: 'Gundapu Odelu (s/o Lingaiah)', money: 501, address: 'NA', status: 0 },
  { id: 29, name: 'Mudidhe Ramesh', money: 200, address: 'NA', status: 0 },
  { id: 30, name: 'Burra Rajaiah (RTC)', money: 200, address: 'NA', status: 0 },
  { id: 31, name: 'Guggili Sagar', money: 200, address: 'NA', status: 0 },
  { id: 32, name: 'Gundapu Srinivas (s/o Lingaiah)', money: 501, address: 'NA', status: 0 },
  { id: 33, name: 'Gundapu Devendar', money: 200, address: 'NA', status: 0 },
  { id: 34, name: 'Challa Sravan', money: 200, address: 'NA', status: 0 },
  { id: 35, name: 'Bollena Ravindar', money: 200, address: 'NA', status: 0 },
  { id: 36, name: 'Gajula Ravindar', money: 200, address: 'NA', status: 0 },
  { id: 37, name: 'Daddanala Rajendar', money: 500, address: 'Nagaram', status: 0 },
  { id: 38, name: 'Lakkam Ramanaiah', money: 500, address: 'Nagaram', status: 0 },
  { id: 39, name: 'Gundapu Lingaiah (Thalla s/o Komuraiah)', money: 500, address: 'NA', status: 0 },
  { id: 40, name: 'Gundapu Rajendar (s/o Machaiah)', money: 200, address: 'NA', status: 0 },
  { id: 41, name: 'Soora Kumaraswamy', money: 2000, address: 'Hanamkonda', status: 0 },
  { id: 42, name: 'Bollena Prathap', money: 500, address: 'NA', status: 0 },
  { id: 43, name: 'Gundapu Shanker', money: 500, address: 'NA', status: 0 },
  { id: 44, name: 'Lingala Raju', money: 200, address: 'Pulkurthi', status: 0 },
  { id: 45, name: 'Gundapu Raju', money: 200, address: 'NA', status: 0 },
  { id: 46, name: 'Abbaraboina Srinivas', money: 200, address: 'NA', status: 0 },
  { id: 47, name: 'Pechala Sarangam', money: 200, address: 'NA', status: 0 },
  { id: 48, name: 'Dubasi Rajamouli', money: 201, address: 'Pulkurthi', status: 0 },
  { id: 49, name: 'Baireni Hamsaiah', money: 100, address: 'NA', status: 0 },
  { id: 50, name: 'Janagani Babu', money: 216, address: 'Dubai', status: 0 },
  { id: 51, name: 'Soora Yadaiah', money: 500, address: 'Yellampelly', status: 0 },
  { id: 52, name: 'Gundapu Sammaiah', money: 100, address: 'NA', status: 0 },
  { id: 53, name: 'Gundapu Thirupathi (IT)', money: 200, address: 'NA', status: 0 },
  { id: 54, name: 'Thalla Veersham', money: 1000, address: 'Hanamkonda', status: 0 },
  { id: 55, name: 'Thalla Venkatesh', money: 1000, address: 'Hanamkonda', status: 0 },
  { id: 56, name: 'Thalla Ramesh', money: 1000, address: 'Hanamkonda', status: 0 },
  { id: 57, name: 'Gajula Rajendar', money: 216, address: 'NA', status: 0 },
  { id: 58, name: 'Kavati Krishnamurthi', money: 201, address: 'NA', status: 0 },
  { id: 59, name: 'Akuthota Rakesh', money: 200, address: 'NA', status: 0 },
  { id: 60, name: 'Bollam Yadagari', money: 100, address: 'NA', status: 0 },
  { id: 61, name: 'Baasam Swamy', money: 100, address: 'NA', status: 0 },
  { id: 62, name: 'Bollam Sambaiah', money: 100, address: 'NA', status: 0 },
  { id: 63, name: 'Bollena Surendar', money: 101, address: 'Shyampeta', status: 0 },
  { id: 64, name: 'Bollam Ravindar', money: 101, address: 'NA', status: 0 },
  { id: 65, name: 'Salla Sadanandam (Bookstall)', money: 1016, address: 'NA', status: 0 },
  { id: 66, name: 'Salla Sathish', money: 1016, address: 'NA', status: 0 },
  { id: 67, name: 'Lakkam Prakash', money: 500, address: 'NA', status: 0 },
  { id: 68, name: 'Gundapu Lingamurthy', money: 201, address: 'NA', status: 0 },
  { id: 69, name: 'Lakkakula Ravikumar', money: 201, address: 'NA', status: 0 },
  { id: 70, name: 'Jangili Ashok', money: 201, address: 'NA', status: 0 },
  { id: 71, name: 'Nutenki Suresh', money: 200, address: 'NA', status: 0 },
  { id: 72, name: 'Koduri Thirupathi', money: 200, address: 'NA', status: 0 },
  { id: 73, name: 'Gundapu Odelu (s/o Mallaiah)', money: 200, address: 'NA', status: 0 },
  { id: 74, name: 'Mittipelly Ravi Kumar', money: 200, address: 'NA', status: 0 },
  { id: 75, name: 'MD Yak Pasha (s/o Raheem Friend)', money: 500, address: 'Madannapet', status: 0 },
  { id: 76, name: 'Kodari Sambaiah (s/o Komuraiah)', money: 200, address: 'Madannapet', status: 0 },
  { id: 77, name: 'Gundapu Santhosh (s/o Lingaiah)', money: 200, address: 'NA', status: 0 },
  { id: 78, name: 'Gundapu Suresh (s/o Lingaiah)', money: 200, address: 'NA', status: 0 },
  { id: 79, name: 'Gundapu Venkateshwarlu', money: 216, address: 'NA', status: 0 },
  { id: 80, name: 'Thota Rajamouli', money: 516, address: 'Hyd', status: 0 },
  { id: 81, name: 'Gundapu Rajendar (s/o Odelu)', money: 216, address: 'NA', status: 0 },
  { id: 82, name: 'Panchagiri Sridhar', money: 1000, address: 'Barenpally', status: 0 },
  { id: 83, name: 'Pusa Kumaraswamy', money: 500, address: 'Kakarapeta', status: 0 },
  { id: 84, name: 'Adapa Nagaraju', money: 1000, address: 'Surampeta', status: 0 },
  { id: 85, name: 'Edla Bagya', money: 500, address: 'Madannapet', status: 0 },
  { id: 86, name: 'Eggadi Raju (s/o Sambaiah)', money: 200, address: 'NA', status: 0 },
  { id: 87, name: 'Thippani Sambaiah (s/o Rajakomuraiah)', money: 200, address: 'NA', status: 0 },
  { id: 88, name: 'Gangadri Rahul Kumar', money: 500, address: 'Hanamkonda', status: 0 },
  { id: 89, name: 'Dubbakula Sarangam', money: 200, address: 'NA', status: 0 },
  { id: 90, name: 'Dubbakula Rajgopal', money: 200, address: 'NA', status: 0 },
  { id: 91, name: 'Vadde Thirupathaiah (Army)', money: 200, address: 'NA', status: 0 },
  { id: 92, name: 'Bollena Saraiah', money: 500, address: 'NA', status: 0 },
  { id: 93, name: 'Bonagiri Raju', money: 500, address: 'Jammikunta', status: 0 },
  { id: 94, name: 'Martha Sadaiah', money: 1116, address: 'Barenpally', status: 0 },
  { id: 95, name: 'Thippani Sambaiah (s/o Rajaiah)', money: 201, address: 'NA', status: 0 },
  { id: 96, name: 'Adapa Srikanth', money: 200, address: 'Hanamkonda', status: 0 },
  { id: 97, name: 'Panchagiri Sadaiah', money: 200, address: 'Hanamkonda', status: 0 },
  { id: 98, name: 'Kaadari Ilaiah', money: 200, address: 'NA', status: 0 },
  { id: 99, name: 'Perugu Raju', money: 200, address: 'Nagaram', status: 0 },
  { id: 100, name: 'Gaade Laxmipathi', money: 1116, address: 'NA', status: 0 },
  { id: 101, name: 'Koyyada Sambaiah (Vijaya)', money: 200, address: 'Madannapet', status: 0 },
  { id: 102, name: 'G. Rajendar Aruna', money: 500, address: 'Hunter Road, Hanamkonda', status: 0 },
  { id: 103, name: 'Koduri Raju', money: 200, address: 'NA', status: 0 },
  { id: 104, name: 'Kanchi Manohar (Rajesh)', money: 516, address: 'NA', status: 0 },
  { id: 105, name: 'Pudhukonda Vani (Dananjaya)', money: 201, address: 'NA', status: 0 },
  { id: 106, name: 'Gundapu Rajendar (s/o Narsaiah Yengari)', money: 2016, address: 'NA', status: 0 },
  { id: 107, name: 'Gundapu Ramesh (MPTC)', money: 200, address: 'NA', status: 0 },
  { id: 108, name: 'Munjamu Raju (s/o Chandraiah)', money: 500, address: 'Ramnagar', status: 0 },
  { id: 109, name: 'Gorre Saraiah', money: 200, address: 'NA', status: 0 },
  { id: 110, name: 'Manda Rajakka', money: 500, address: 'Warangal', status: 0 },
  { id: 111, name: 'Baireni Raju', money: 200, address: 'NA', status: 0 },
  { id: 112, name: 'Lakkakula Rakesh', money: 200, address: 'NA', status: 0 },
  { id: 113, name: 'Lakkakula Narsaiah', money: 200, address: 'NA', status: 0 },
  { id: 114, name: 'Thangeda Mahendar', money: 500, address: 'Sooraram', status: 0 },
  { id: 115, name: 'Madishetty Madhukar', money: 516, address: 'Arepally', status: 0 },
  { id: 116, name: 'Pechala Shivakrishna', money: 500, address: 'NA', status: 0 },
  { id: 117, name: 'Madipelly Thirupathi', money: 200, address: 'Madannapet', status: 0 },
  { id: 118, name: 'Gundapu Raju (s/o Veeraswamy)', money: 200, address: 'NA', status: 0 },
  { id: 119, name: 'Gundapu Vasu (s/o Odelu)', money: 200, address: 'NA', status: 0 },
  { id: 120, name: 'Gundapu Srinivas (s/o Odelu)', money: 200, address: 'NA', status: 0 },
  { id: 121, name: 'Gundapu Sampath', money: 200, address: 'NA', status: 0 },
  { id: 122, name: 'Lakkam Ramesh', money: 200, address: 'Yellampally', status: 0 },
  { id: 123, name: 'Vadde Krishnamurthi', money: 201, address: 'NA', status: 0 },
  { id: 124, name: 'Thagellapelly Pedhanna', money: 200, address: 'NA', status: 0 },
  { id: 125, name: 'Nukenti Komuramallu', money: 200, address: 'NA', status: 0 },
  { id: 126, name: 'Thagellapelly Ramesh', money: 200, address: 'NA', status: 0 },
  { id: 127, name: 'Abbaraveni Anil (Phonepay)', money: 216, address: 'NA', status: 0 },
  { id: 128, name: 'Thippani Pedha Ramesh (Phonepay)', money: 216, address: 'NA', status: 0 },
  { id: 129, name: 'Gannu Sathish Kumar', money: 500, address: 'Pulkurthi', status: 0 },
  { id: 130, name: 'Rura Chandar', money: 200, address: 'Pulkurthy', status: 0 },
  { id: 131, name: 'Manda Prakash (Shiva Phonepay)', money: 3000, address: 'Yellampally', status: 0 },
  { id: 132, name: 'Nukenti Ramulu', money: 200, address: 'Yellampally', status: 0 },
  { id: 133, name: 'Sunkari Dilip (Nagamani Phonepay)', money: 1116, address: 'NA', status: 0 },
  { id: 134, name: 'Gajula Srinivas (Phonepay)', money: 501, address: 'Karimnagar', status: 0 },
  { id: 135, name: 'Kosari Raju (Lingala, Mallaiah)', money: 1000, address: 'NA', status: 0 }
];
export default data;